name: Add new and updated issues to Needs Review

env:
  eng_usernames: allisonport-db scottsand-db tdas vkorukanti zsxwing
  devrel_usernames: dennyglee MrPowers nkarpov vinijaiswal

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  automate-new-updated-issues:
    if: ${{ !github.event.issue.pull_request &&
      !contains('allisonport-db scottsand-db tdas vkorukanti zsxwing dennyglee MrPowers nkarpov vinijaiswal', github.event.sender.login) }}
    runs-on: ubuntu-latest
    steps:
      - name: Move to Needs Review (ENG)
        if: ${{ github.event.issue.assignee != null && contains(env.eng_usernames, github.event.issue.assignee.login) }}
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: oss-delta-issues
          column: Needs Review (ENG)
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}
      - name: Move to Needs Review
        if: ${{ github.event.issue.assignee == null || contains(env.devrel_usernames, github.event.issue.assignee.login) }}
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: oss-delta-issues
          column: Needs Review
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}
